[project]
name = ""
version = ""
description = ""
authors = [
    {name = "foo", email = "foo.example.com"},
]
dependencies = [
    "apache-beam[gcp]>=2.40.0",
]
requires-python = ">=3.8, <=3.11"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
